# Generated by Django 4.1.7 on 2023-03-06 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_alter_embasy_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('title', models.CharField(max_length=150, verbose_name='Nomi')),
                ('icon', models.ImageField(upload_to='projects/document_type/icons/', verbose_name='Rasmi')),
            ],
            options={
                'verbose_name': 'Hujjat turi',
                'verbose_name_plural': 'Hujjat turlari',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('title', models.CharField(max_length=150, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=150, verbose_name='Slugi')),
                ('icon', models.ImageField(upload_to='projects/project/icon/', verbose_name='Rasmi')),
                ('short_description', models.CharField(max_length=250, verbose_name='Qisqa tavsif')),
                ('description', models.TextField(verbose_name='Tavsifi')),
                ('video_link', models.URLField(verbose_name='Video uchun havola')),
                ('team_members', models.ManyToManyField(to='main.management_staff', verbose_name='Jamoa a`zolari')),
            ],
            options={
                'verbose_name': 'Loyiha',
                'verbose_name_plural': 'Loyihalar',
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('title', models.CharField(max_length=100, verbose_name='Nomi')),
                ('icon', models.ImageField(upload_to='projects/objective/icons/', verbose_name='Rasmi')),
                ('text', models.TextField(verbose_name='Maqsad matni')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Loyiha')),
            ],
            options={
                'verbose_name': 'Loyiha uchun maqsad',
                'verbose_name_plural': 'Loyiha uchun maqsadlar',
            },
        ),
        migrations.CreateModel(
            name='Document_for_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('title', models.CharField(max_length=150, verbose_name='Nomi')),
                ('size', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Hajmi')),
                ('file', models.FileField(upload_to='projects/document/files/', verbose_name='Hujjat fayli')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Loyiha')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.document_type')),
            ],
            options={
                'verbose_name': 'Hujjat',
                'verbose_name_plural': 'Hujjatlar',
            },
        ),
    ]
