# Generated by Django 4.1.7 on 2023-03-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Muallif'),
        ),
        migrations.AddField(
            model_name='book',
            name='author_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Muallif'),
        ),
        migrations.AddField(
            model_name='book',
            name='author_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Muallif'),
        ),
        migrations.AddField(
            model_name='book',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Tavsifi'),
        ),
        migrations.AddField(
            model_name='book',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Tavsifi'),
        ),
        migrations.AddField(
            model_name='book',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Tavsifi'),
        ),
        migrations.AddField(
            model_name='book',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='book',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='book',
            name='title_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='category_book',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='category_book',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='category_book',
            name='name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='category_for_event',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='category_for_event',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='category_for_event',
            name='title_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='document_type',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='document_type',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='document_type',
            name='title_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='event',
            name='address_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Manzili'),
        ),
        migrations.AddField(
            model_name='event',
            name='address_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Manzili'),
        ),
        migrations.AddField(
            model_name='event',
            name='address_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Manzili'),
        ),
        migrations.AddField(
            model_name='event',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Tadbir haqida ma`lumot'),
        ),
        migrations.AddField(
            model_name='event',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Tadbir haqida ma`lumot'),
        ),
        migrations.AddField(
            model_name='event',
            name='content_uz',
            field=models.TextField(null=True, verbose_name='Tadbir haqida ma`lumot'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Sarlavhasi'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Sarlavhasi'),
        ),
        migrations.AddField(
            model_name='event',
            name='title_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Sarlavhasi'),
        ),
        migrations.AddField(
            model_name='language',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='language',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='language',
            name='title_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='qa',
            name='answer_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Javob'),
        ),
        migrations.AddField(
            model_name='qa',
            name='answer_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Javob'),
        ),
        migrations.AddField(
            model_name='qa',
            name='answer_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Javob'),
        ),
        migrations.AddField(
            model_name='qa',
            name='question_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Savol'),
        ),
        migrations.AddField(
            model_name='qa',
            name='question_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Savol'),
        ),
        migrations.AddField(
            model_name='qa',
            name='question_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Savol'),
        ),
        migrations.AddField(
            model_name='tag_for_qa',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='tag_for_qa',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='tag_for_qa',
            name='title_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Nomi'),
        ),
    ]
