# Generated by Django 4.1.7 on 2023-03-06 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('title', models.CharField(max_length=150, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Shart',
                'verbose_name_plural': 'Shartlar',
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('title', models.CharField(max_length=150, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Talab',
                'verbose_name_plural': 'Talablar',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('full_name', models.CharField(max_length=150, verbose_name='F.I.SH')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('file', models.FileField(upload_to='career/resume/files/', verbose_name='Fayl')),
            ],
            options={
                'verbose_name': 'Rezyume',
                'verbose_name_plural': 'Rezyumelar',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('title', models.CharField(max_length=150, verbose_name='Nomi')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('address', models.CharField(max_length=250, verbose_name='Manzili')),
                ('start_salary', models.PositiveIntegerField(default=0, verbose_name='Boshlang`ich maosh')),
                ('end_salary', models.PositiveIntegerField(default=0, verbose_name='Eng yuqori maosh')),
                ('salary_type', models.CharField(choices=[('Cash', 'Naqd'), ('Conversation', 'Suhbat orqali')], max_length=20, verbose_name='Maosh turi')),
                ('description', models.TextField(verbose_name='Tavsifi')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Ko`rishlar soni')),
                ('condition', models.ManyToManyField(to='career.condition', verbose_name='Shart')),
                ('requirement', models.ManyToManyField(to='career.requirement', verbose_name='Talab')),
            ],
            options={
                'verbose_name': 'Bo`sh ish o`rni',
                'verbose_name_plural': 'Bo`sh ish o`rinlari',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('full_name', models.CharField(max_length=150, verbose_name='F.I.SH')),
                ('email', models.EmailField(max_length=100, verbose_name='Elektron pochta')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('resume_file', models.FileField(upload_to='career/volunteer/resume_file/', verbose_name='Fayl')),
            ],
            options={
                'verbose_name': 'Volontyor',
                'verbose_name_plural': 'Volontyorlar',
            },
        ),
        migrations.CreateModel(
            name='Work_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('name', models.CharField(max_length=50, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Ish turi',
                'verbose_name_plural': 'Ish turlari',
            },
        ),
        migrations.CreateModel(
            name='Vacancy_resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('resume_file', models.FileField(upload_to='career/vacancy_resume/files/', verbose_name='Fayli')),
                ('vacancy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.vacancy', verbose_name='Vakansiya')),
            ],
            options={
                'verbose_name': 'Vakansiyadagi rezyume',
                'verbose_name_plural': 'Vakansiyadagi rezyumelar',
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='type_work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='career.work_type'),
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O`zgartirilgan vaqti')),
                ('full_name', models.CharField(max_length=150, verbose_name='F.I.SH')),
                ('email', models.EmailField(max_length=100, verbose_name='Elektron pochta')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('address', models.CharField(max_length=150, verbose_name='Manzili')),
                ('birthday', models.DateField(verbose_name='Tug`ilgan sanasi')),
                ('business_area', models.CharField(max_length=200, verbose_name='Faoliyat sohasi')),
                ('start_date', models.DateField(verbose_name='Boshlanish vaqti')),
                ('education', models.CharField(max_length=150, verbose_name='O`qish joyi')),
                ('speciality', models.CharField(max_length=150, verbose_name='Yo`nalishi')),
                ('year_admission', models.DateField(verbose_name='Qabul qilingan yili')),
                ('year_ending', models.DateField(verbose_name='Tugash yili')),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='GPA')),
                ('experience', models.CharField(max_length=150, verbose_name='Tajriba')),
                ('key_skills', models.CharField(max_length=150, verbose_name='Ko`nikmalari')),
                ('resume', models.FileField(upload_to='career/internship/resume_file/', verbose_name='Rezyume fayli')),
                ('work_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='career.work_type')),
            ],
            options={
                'verbose_name': 'Amaliyot o`tash uchun nomzod',
                'verbose_name_plural': 'Amaliyot o`tash uchun nomzodlar',
            },
        ),
    ]
