# Generated by Django 4.1.7 on 2023-03-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='condition',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='condition',
            name='title_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='title_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='address_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Manzili'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='address_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Manzili'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='address_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='Manzili'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Tavsifi'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Tavsifi'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Tavsifi'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_type_en',
            field=models.CharField(choices=[('Cash', 'Naqd'), ('Conversation', 'Suhbat orqali')], max_length=20, null=True, verbose_name='Maosh turi'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_type_ru',
            field=models.CharField(choices=[('Cash', 'Naqd'), ('Conversation', 'Suhbat orqali')], max_length=20, null=True, verbose_name='Maosh turi'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_type_uz',
            field=models.CharField(choices=[('Cash', 'Naqd'), ('Conversation', 'Suhbat orqali')], max_length=20, null=True, verbose_name='Maosh turi'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='full_name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='F.I.SH'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='full_name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='F.I.SH'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='full_name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='F.I.SH'),
        ),
        migrations.AddField(
            model_name='work_type',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='work_type',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='work_type',
            name='name_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Nomi'),
        ),
    ]
