# Generated by Django 4.1.7 on 2023-03-06 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_condition_title_en_condition_title_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='salary_type_en',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='salary_type_ru',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='salary_type_uz',
        ),
    ]
