# Generated by Django 4.1.7 on 2023-03-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_remove_vacancy_salary_type_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='end_salary',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Eng yuqori maosh'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='start_salary',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Boshlang`ich maosh'),
        ),
    ]
