# Generated by Django 4.1.7 on 2023-03-06 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='embasy',
            options={'verbose_name': 'Elchixona', 'verbose_name_plural': 'Elchixonalar'},
        ),
    ]
