# Generated by Django 4.1.7 on 2023-03-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_embasy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission_day',
            name='end_day_en',
            field=models.CharField(choices=[('Monday', 'Dushanba'), ('Tuesday', 'Seshanba'), ('Wednesday', 'Chorshanba'), ('Thursday', 'Payshanba'), ('Friday', 'Juma'), ('Saturday', 'Shanba'), ('Sunday', 'Yakshanba')], default='Friday', max_length=20, null=True, verbose_name='Tigash kuni'),
        ),
        migrations.AddField(
            model_name='admission_day',
            name='end_day_ru',
            field=models.CharField(choices=[('Monday', 'Dushanba'), ('Tuesday', 'Seshanba'), ('Wednesday', 'Chorshanba'), ('Thursday', 'Payshanba'), ('Friday', 'Juma'), ('Saturday', 'Shanba'), ('Sunday', 'Yakshanba')], default='Friday', max_length=20, null=True, verbose_name='Tigash kuni'),
        ),
        migrations.AddField(
            model_name='admission_day',
            name='end_day_uz',
            field=models.CharField(choices=[('Monday', 'Dushanba'), ('Tuesday', 'Seshanba'), ('Wednesday', 'Chorshanba'), ('Thursday', 'Payshanba'), ('Friday', 'Juma'), ('Saturday', 'Shanba'), ('Sunday', 'Yakshanba')], default='Friday', max_length=20, null=True, verbose_name='Tigash kuni'),
        ),
        migrations.AddField(
            model_name='admission_day',
            name='start_day_en',
            field=models.CharField(choices=[('Monday', 'Dushanba'), ('Tuesday', 'Seshanba'), ('Wednesday', 'Chorshanba'), ('Thursday', 'Payshanba'), ('Friday', 'Juma'), ('Saturday', 'Shanba'), ('Sunday', 'Yakshanba')], default='Monday', max_length=20, null=True, verbose_name='Boshlanish kuni'),
        ),
        migrations.AddField(
            model_name='admission_day',
            name='start_day_ru',
            field=models.CharField(choices=[('Monday', 'Dushanba'), ('Tuesday', 'Seshanba'), ('Wednesday', 'Chorshanba'), ('Thursday', 'Payshanba'), ('Friday', 'Juma'), ('Saturday', 'Shanba'), ('Sunday', 'Yakshanba')], default='Monday', max_length=20, null=True, verbose_name='Boshlanish kuni'),
        ),
        migrations.AddField(
            model_name='admission_day',
            name='start_day_uz',
            field=models.CharField(choices=[('Monday', 'Dushanba'), ('Tuesday', 'Seshanba'), ('Wednesday', 'Chorshanba'), ('Thursday', 'Payshanba'), ('Friday', 'Juma'), ('Saturday', 'Shanba'), ('Sunday', 'Yakshanba')], default='Monday', max_length=20, null=True, verbose_name='Boshlanish kuni'),
        ),
        migrations.AddField(
            model_name='branch',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='branch',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='branch',
            name='title_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='consulate',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='consulate',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='consulate',
            name='title_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='title_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='embasy',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='embasy',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='embasy',
            name='title_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='employee_abroad',
            name='full_name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='F.I.SH'),
        ),
        migrations.AddField(
            model_name='employee_abroad',
            name='full_name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='F.I.SH'),
        ),
        migrations.AddField(
            model_name='employee_abroad',
            name='full_name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='F.I.SH'),
        ),
        migrations.AddField(
            model_name='employee_abroad',
            name='position_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Lavozimi'),
        ),
        migrations.AddField(
            model_name='employee_abroad',
            name='position_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Lavozimi'),
        ),
        migrations.AddField(
            model_name='employee_abroad',
            name='position_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Lavozimi'),
        ),
        migrations.AddField(
            model_name='employee_abroad',
            name='tasks_en',
            field=models.TextField(null=True, verbose_name='Vziflari'),
        ),
        migrations.AddField(
            model_name='employee_abroad',
            name='tasks_ru',
            field=models.TextField(null=True, verbose_name='Vziflari'),
        ),
        migrations.AddField(
            model_name='employee_abroad',
            name='tasks_uz',
            field=models.TextField(null=True, verbose_name='Vziflari'),
        ),
        migrations.AddField(
            model_name='expense',
            name='reason_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Sababi'),
        ),
        migrations.AddField(
            model_name='expense',
            name='reason_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Sababi'),
        ),
        migrations.AddField(
            model_name='expense',
            name='reason_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Sababi'),
        ),
        migrations.AddField(
            model_name='management_staff',
            name='bio_en',
            field=models.TextField(null=True, verbose_name='Biografiyasi'),
        ),
        migrations.AddField(
            model_name='management_staff',
            name='bio_ru',
            field=models.TextField(null=True, verbose_name='Biografiyasi'),
        ),
        migrations.AddField(
            model_name='management_staff',
            name='bio_uz',
            field=models.TextField(null=True, verbose_name='Biografiyasi'),
        ),
        migrations.AddField(
            model_name='management_staff',
            name='full_name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='F.I.SH'),
        ),
        migrations.AddField(
            model_name='management_staff',
            name='full_name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='F.I.SH'),
        ),
        migrations.AddField(
            model_name='management_staff',
            name='full_name_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='F.I.SH'),
        ),
        migrations.AddField(
            model_name='management_staff',
            name='position_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Lavozimi'),
        ),
        migrations.AddField(
            model_name='management_staff',
            name='position_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Lavozimi'),
        ),
        migrations.AddField(
            model_name='management_staff',
            name='position_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Lavozimi'),
        ),
        migrations.AddField(
            model_name='management_staff',
            name='tasks_en',
            field=models.TextField(null=True, verbose_name='Vazifalari'),
        ),
        migrations.AddField(
            model_name='management_staff',
            name='tasks_ru',
            field=models.TextField(null=True, verbose_name='Vazifalari'),
        ),
        migrations.AddField(
            model_name='management_staff',
            name='tasks_uz',
            field=models.TextField(null=True, verbose_name='Vazifalari'),
        ),
        migrations.AddField(
            model_name='partner',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='partner',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='partner',
            name='title_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='partner',
            name='type_en',
            field=models.CharField(choices=[('State', 'Davlat'), ('Own', 'Xususiy')], max_length=20, null=True, verbose_name='Homiy turi'),
        ),
        migrations.AddField(
            model_name='partner',
            name='type_ru',
            field=models.CharField(choices=[('State', 'Davlat'), ('Own', 'Xususiy')], max_length=20, null=True, verbose_name='Homiy turi'),
        ),
        migrations.AddField(
            model_name='partner',
            name='type_uz',
            field=models.CharField(choices=[('State', 'Davlat'), ('Own', 'Xususiy')], max_length=20, null=True, verbose_name='Homiy turi'),
        ),
        migrations.AddField(
            model_name='payment',
            name='full_name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Ism, familiya'),
        ),
        migrations.AddField(
            model_name='payment',
            name='full_name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Ism, familiya'),
        ),
        migrations.AddField(
            model_name='payment',
            name='full_name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Ism, familiya'),
        ),
        migrations.AddField(
            model_name='useful_links',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='useful_links',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='useful_links',
            name='title_uz',
            field=models.CharField(max_length=150, null=True, verbose_name='Nomi'),
        ),
    ]
